name: watson-bot

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    command: postgres -c shared_preload_libraries=pg_textsearch,pg_search
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4

  backend: &backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/pyproject.toml
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: /app/start.sh
    environment:
      IS_DOCKER: true
    env_file:
      - .env

  worker:
    <<: *backend
    image: worker
    depends_on:
      - db
      - redis
    ports: []
    command: /app/start-worker.sh

  beat:
    <<: *backend
    image: beat
    depends_on:
      - db
      - redis
    ports: []
    command: /app/start-beat.sh

  discord: &discord
    build:
      context: ./discord
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./discord
          target: /app
        - action: rebuild
          path: ./discord/pyproject.toml
    env_file:
      - .env

volumes:
  db-data:
