name: watson

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  backend: &backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/pyproject.toml
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  db-data:
