name: watson-bot

networks:
  back: {}

volumes:
  db-data:
  redis-data:

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    command: postgres -c shared_preload_libraries=pg_search
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [back]

  redis:
    image: redis:8.4
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [back]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /app/start.sh
    environment:
      IS_DOCKER: "true"
    env_file: [.env]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health/ || exit 1"]
      interval: 2m
      timeout: 3s
      retries: 1
    restart: unless-stopped
    networks: [back]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /app/start-worker.sh
    env_file: [.env]
    restart: unless-stopped
    networks: [back]

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    command: /app/start-beat.sh
    env_file: [.env]
    restart: unless-stopped
    networks: [back]

  cloudflared:
    image: cloudflare/cloudflared:2025.10.1
    restart: unless-stopped
    networks: [back]
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN} --protocol http2
    env_file: [.env]
