name: watson-bot

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
  discord: &discord
    build:
      context: ./discord
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./discord
          target: /app
        - action: rebuild
          path: ./discord/pyproject.toml
    env_file:
      - ./discord/.env

volumes:
  db-data:
