[project]
name = "watson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=7.1.0",
    "marimo>=0.17.8",
    "mistralai>=1.9.11",
    "pre-commit>=4.3.0",
    "pydantic-ai==1.70",
    "pydantic-ai-slim[mistral,openrouter]>=1.65.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.4",
    "sqlalchemy-paradedb==0.6.0",
]

[tool.ruff.lint]
extend-select = ["FBT"]

[tool.uv]
exclude-newer = "2 weeks"