"""inital migrations

Revision ID: a21035b8bd24
Revises:
Create Date: 2025-07-09 08:03:41.798442

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "a21035b8bd24"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
