"""Initial migrations

Revision ID: 02934bcf1424
Revises:
Create Date: 2025-07-14 15:37:03.453132

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "02934bcf1424"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
