"""add tags

Revision ID: 78b5e3a99d37
Revises: c558f6558964
Create Date: 2026-08-08 22:48:45.783879

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78b5e3a99d37"
down_revision: str | None = "c558f6558964"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "slug",
            sa.String(length=50),
            nullable=False,
            comment="Immutable identifier stored in transactions.tags",
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="When to apply this tag; rendered into the agent's instructions",
        ),
        sa.Column("is_pot", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("exclude_from_monthly", sa.Boolean(), nullable=False),
        sa.Column(
            "limit_amount",
            sa.Float(),
            nullable=True,
            comment="Null means the pot tracks spend with no limit",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_tags_status", "tags", ["status"], unique=False)
    op.add_column(
        "transactions",
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Tag slugs; validated against tags.slug before write",
        ),
    )
    op.create_index(
        "ix_transactions_tags",
        "transactions",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transactions_tags", table_name="transactions", postgresql_using="gin"
    )
    op.drop_column("transactions", "tags")
    op.drop_index("ix_tags_status", table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
