"""dd people and ledger table

Revision ID: d3ae1bb46348
Revises: e26e44bdac0d
Create Date: 2026-09-06 22:44:23.067227

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3ae1bb46348"
down_revision: str | None = "e26e44bdac0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column(
            "nickname",
            sa.String(length=50),
            nullable=False,
            comment="How the user refers to them; the handle tools resolve",
        ),
        sa.Column(
            "full_name",
            sa.String(length=200),
            nullable=True,
            comment="Formal name, for emails and invoices",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "amount",
            sa.Float(),
            nullable=False,
            comment="Signed: + they owe you, - you owe them",
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "transaction_id",
            sa.UUID(),
            nullable=True,
            comment="The expense this entry was split out of, when there was one",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ledger_entries_person_id_date",
        "ledger_entries",
        ["person_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ledger_entries_person_id_date", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_table("people")
    # ### end Alembic commands ###
