"""add bm25 index to transactions

Revision ID: 396f1c2f82dc
Revises: 14bff34d431a
Create Date: 2026-05-09 16:14:24.524851

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "396f1c2f82dc"
down_revision: str | None = "14bff34d431a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_transactions_bm25",
        "transactions",
        [
            sa.literal_column("id"),
            sa.literal_column("title"),
            sa.literal_column("description"),
        ],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transactions_bm25",
        table_name="transactions",
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    # ### end Alembic commands ###
