"""Add DiscordMessage Table

Revision ID: 33192f466072
Revises: 396f1c2f82dc
Create Date: 2026-06-13 16:06:53.866129

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33192f466072"
down_revision: str | None = "396f1c2f82dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_conversations",
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "message_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_index(
        "ix_discord_conversations_message_ids",
        "discord_conversations",
        ["message_ids"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_discord_conversations_message_ids",
        table_name="discord_conversations",
        postgresql_using="gin",
    )
    op.drop_table("discord_conversations")
    # ### end Alembic commands ###
