"""initial commit

Revision ID: 4818b1e7d985
Revises:
Create Date: 2025-03-07 21:41:29.392437

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "4818b1e7d985"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
