"""enable extensions

Revision ID: 5d378a1fb8b5
Revises: 0ab1840f7b79
Create Date: 2026-02-18 14:43:02.326362

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d378a1fb8b5"
down_revision: str | None = "0ab1840f7b79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")  # pgvector
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_textsearch")  # BM25 search
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS pg_textsearch")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
