"""Add indices on the transaciton table

Revision ID: d7a464a3187e
Revises: 5d378a1fb8b5
Create Date: 2026-02-19 12:56:35.659279

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7a464a3187e"
down_revision: str | None = "5d378a1fb8b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.create_index(
        "ix_transaction_description_bm25",
        "transactions",
        ["description"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"text_config": "english"},
    )
    op.create_index(
        "ix_transaction_title_bm25",
        "transactions",
        ["title"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"text_config": "english"},
    )
    op.create_index(
        "ix_transactions_category", "transactions", ["category"], unique=False
    )
    op.create_index("ix_transactions_date", "transactions", ["date"], unique=False)
    op.create_index(
        "ix_transactions_is_expense", "transactions", ["is_expense"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_is_expense", table_name="transactions")
    op.drop_index("ix_transactions_date", table_name="transactions")
    op.drop_index("ix_transactions_category", table_name="transactions")
    op.drop_index(
        "ix_transaction_title_bm25",
        table_name="transactions",
        postgresql_using="bm25",
        postgresql_with={"text_config": "english"},
    )
    op.drop_index(
        "ix_transaction_description_bm25",
        table_name="transactions",
        postgresql_using="bm25",
        postgresql_with={"text_config": "english"},
    )
    op.alter_column(
        "transactions",
        "title",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
